### ISSUE TITLE
Can't install on OSX 10.9.2

### ISSUE THREAD

**Issue by davidblewett** [chtd/psycopg2cffi#20]
I have PostgreSQL 9.3 installed via MacPorts (and `pg_config` is on my path). I am using PyPy 2.2.1 (also installed from MacPorts). I've tried using pip to install from PyPI, downloading the tarball and running develop / install and cloning the repo and trying it but they all hit this error.

It seems that the `setup.py` script is erroring out before it gets to the point of calling `pg_config`:

```
Thu May  1, 07:15 | /Users/dblewett/src/psycopg2cffi-2.5
kell% pypy setup.py build_py --pg-config=/opt/local/bin/pg_config
psycopg2cffi/_impl/__pycache__/_cffi__g3212cffex2df7bd7b.c:26:10: fatal error: 'postgres_ext.h' file not found
#include <postgres_ext.h>
         ^
1 error generated.
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "setup.py", line 250, in <module>
    import psycopg2cffi._impl.libpq
  File "/Users/dblewett/src/psycopg2cffi-2.5/psycopg2cffi/__init__.py", line 4, in <module>
    from psycopg2cffi import extensions
  File "/Users/dblewett/src/psycopg2cffi-2.5/psycopg2cffi/extensions.py", line 36, in <module>
    from psycopg2cffi._impl import connection as _connection
  File "/Users/dblewett/src/psycopg2cffi-2.5/psycopg2cffi/_impl/connection.py", line 7, in <module>
    from psycopg2cffi._impl import exceptions
  File "/Users/dblewett/src/psycopg2cffi-2.5/psycopg2cffi/_impl/exceptions.py", line 1, in <module>
    from psycopg2cffi._impl.libpq import libpq, ffi
  File "/Users/dblewett/src/psycopg2cffi-2.5/psycopg2cffi/_impl/libpq.py", line 221, in <module>
    ext_package='psycopg2cffi')
  File "/opt/local/lib/pypy/lib_pypy/cffi/api.py", line 339, in verify
    lib = self.verifier.load_library()
  File "/opt/local/lib/pypy/lib_pypy/cffi/verifier.py", line 74, in load_library
    self._compile_module()
  File "/opt/local/lib/pypy/lib_pypy/cffi/verifier.py", line 139, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/opt/local/lib/pypy/lib_pypy/cffi/ffiplatform.py", line 25, in compile
    outputfilename = _build(tmpdir, ext)
  File "/opt/local/lib/pypy/lib_pypy/cffi/ffiplatform.py", line 50, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: CompileError: command 'cc' failed with exit status 1
```

**Comment by houmie** [comment]
I get the same error when I try to compile it. I have installed Postgres with Homebrew.  It says #include "postgres_ext.h"  file not found.

Any advice? Thanks

**Comment by lopuhin** [comment]
@houmie what is the output of ```pg_config | grep -e "^INCLUDEDIR ="```, and is there a file named ```postgres_ext.h"``` in this directory? Also, just in case, could you please paste the command you used to install psycopg2cffi, and complete error output?

**Comment by houmie** [comment]
Thanks for reply.

The output is ```INCLUDEDIR = /usr/local/Cellar/postgresql/9.4.1/include```
yes I can see a ```postgres_ext.h``` in ```/usr/local/Cellar/postgresql/9.4.1/include```

I have installed psycopg2cffi like this:

```sudo pip install psycopg2cffi```

**Comment by lopuhin** [comment]
Thank you! And the error occurs when running pip install command, or on the first import?

**Comment by houmie** [comment]
I am realy sorry for the confusion I have caused.  I mixed up the tabs in my browser.  I was meant to post this to ```https://github.com/Induction/Induction```.   In there I get the error message regarding missing ```postgres_ext.h``` when I try to compile it.

**Comment by lopuhin** [comment]
No problem :)
