### ISSUE TITLE
ImportError: No module named psycopg2._psycopg

### ISSUE THREAD

**Issue by ephillipe** [chtd/psycopg2cffi#28]
``` python
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "server.py", line 7, in <module>
    from server.connection_pool import *
  File "/home/erick/0.13.x/server/connection_pool.py", line 1, in <module>
    from pypgwrap.pool import ThreadedConnectionPool
  File "/home/erick/pypy-karoo/site-packages/pypgwrap/__init__.py", line 1, in <module>
    from connection import connection
  File "/home/erick/pypy-karoo/site-packages/pypgwrap/connection.py", line 1, in <module>
    from psycopg2._psycopg import OperationalError
ImportError: No module named psycopg2._psycopg
```

**Comment by lopuhin** [comment]
Closing, corrent import in the previous comment
