### ISSUE TITLE
Error installing Pypy on Amazon Linux (CentOS)

### ISSUE THREAD

**Issue by ephillipe** [chtd/psycopg2cffi#29]
``` python
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/var/www/karoo.com.br/server.py", line 7, in <module>
    from server.connection_pool import *
  File "/var/www/karoo.com.br/server/connection_pool.py", line 1, in <module>
    from pypgwrap.pool import ThreadedConnectionPool
  File "/opt/python/run/venv-karoo-pypy/site-packages/pypgwrap/__init__.py", line 1, in <module>
    from connection import connection
  File "/opt/python/run/venv-karoo-pypy/site-packages/pypgwrap/connection.py", line 5, in <module>
    from psycopg2.extras import DictCursor, NamedTupleCursor
  File "/opt/python/run/venv-karoo-pypy/site-packages/newrelic-2.34.0.29/newrelic/api/import_hook.py", line 128, in find_module
    __import__(fullname)
  File "/opt/python/run/venv-karoo-pypy/site-packages/psycopg2.py", line 1, in <module>
    from psycopg2cffi import compat
  File "/opt/python/run/venv-karoo-pypy/site-packages/newrelic-2.34.0.29/newrelic/api/import_hook.py", line 128, in find_module
    __import__(fullname)
  File "/opt/python/run/venv-karoo-pypy/site-packages/psycopg2cffi/__init__.py", line 4, in <module>
    from psycopg2cffi import extensions
  File "/opt/python/run/venv-karoo-pypy/site-packages/newrelic-2.34.0.29/newrelic/api/import_hook.py", line 128, in find_module
    __import__(fullname)
  File "/opt/python/run/venv-karoo-pypy/site-packages/psycopg2cffi/extensions.py", line 36, in <module>
    from psycopg2cffi._impl import connection as _connection
  File "/opt/python/run/venv-karoo-pypy/site-packages/psycopg2cffi/_impl/connection.py", line 7, in <module>
    from psycopg2cffi._impl import exceptions
  File "/opt/python/run/venv-karoo-pypy/site-packages/psycopg2cffi/_impl/exceptions.py", line 1, in <module>
    from psycopg2cffi._impl.libpq import libpq, ffi
  File "/opt/python/run/venv-karoo-pypy/site-packages/psycopg2cffi/_impl/libpq.py", line 220, in <module>
    ext_package='psycopg2cffi')
  File "/opt/pypy-2.4/lib_pypy/cffi/api.py", line 340, in verify
    lib = self.verifier.load_library()
  File "/opt/pypy-2.4/lib_pypy/cffi/verifier.py", line 73, in load_library
    self._write_source()
  File "/opt/pypy-2.4/lib_pypy/cffi/verifier.py", line 125, in _write_source
    file = open(self.sourcefilename, 'w')
IOError: [Errno 2] No such file or directory: '/opt/python/run/venv-karoo-pypy/site-packages/psycopg2cffi/_impl/__pycache__/_cffi__g34a829d3xebeb8df8.c'
```

When I run my App on this OS I get this error. If I try on Ubuntu run fine.
On CentOS I use https://github.com/squeaky-pl/portable-pypy (64bits)

**Comment by abrakadavra** [comment]
I got same error on Mac OSX 10.9.5 here.
The package was installed successfully by pip (sudo pip install psycopg2cffi).

Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "server-sv.py", line 9, in <module>
    import models.model
  File "/Users/oyunbileg/cbserver_20150116/MatchingDBServer/models/model.py", line 7, in <module>
    import psycopg2cffi
  File "/Users/oyunbileg/cbserver_20150116/MatchingDBServer/pypy-env/site-packages/psycopg2cffi/__init__.py", line 4, in <module>
    from psycopg2cffi import extensions
  File "/Users/oyunbileg/cbserver_20150116/MatchingDBServer/pypy-env/site-packages/psycopg2cffi/extensions.py", line 36, in <module>
    from psycopg2cffi._impl import connection as _connection
  File "/Users/oyunbileg/cbserver_20150116/MatchingDBServer/pypy-env/site-packages/psycopg2cffi/_impl/connection.py", line 7, in <module>
    from psycopg2cffi._impl import exceptions
  File "/Users/oyunbileg/cbserver_20150116/MatchingDBServer/pypy-env/site-packages/psycopg2cffi/_impl/exceptions.py", line 1, in <module>
    from psycopg2cffi._impl.libpq import libpq, ffi
  File "/Users/oyunbileg/cbserver_20150116/MatchingDBServer/pypy-env/site-packages/psycopg2cffi/_impl/libpq.py", line 220, in <module>
    ext_package='psycopg2cffi')
  File "/usr/local/opt/pypy/lib_pypy/cffi/api.py", line 339, in verify
    lib = self.verifier.load_library()
  File "/usr/local/opt/pypy/lib_pypy/cffi/verifier.py", line 73, in load_library
    self._write_source()
  File "/usr/local/opt/pypy/lib_pypy/cffi/verifier.py", line 125, in _write_source
    file = open(self.sourcefilename, 'w')
IOError: [Errno 2] No such file or directory: '/Users/oyunbileg/cbserver_20150116/MatchingDBServer/pypy-env/site-packages/psycopg2cffi/_impl/__pycache__/_cffi__gdb5bd916x8194cf09.c'

**Comment by abrakadavra** [comment]
There's no directory named "__pycache" under .../pypy-env/site-packages/psycopg2cffi/_impl/.
(Actually, there is no any directory)

**Comment by cfblaeb** [comment]
I also get the exact same error on Ubuntu 14.04.01.
It started after I upgraded pypy and psycopg2cffi from 2.5-alpha0 and 2.5.2 respectively to 2.5 and 2.6.1
After playing around with different versions for a while, I got it to work by setting permissions to 777 for my python folder...
