### ISSUE TITLE
register_type for unicode is crashing for 'unknown' type

### ISSUE THREAD

**Issue by amjith** [chtd/psycopg2cffi#32]
```
>>> import psycopg2cffi as psycopg2
>>> import psycopg2cffi.extensions as ext
>>> c = psycopg2.connect(database='postgres')
>>> cur = c.cursor()
>>> ext.register_type(ext.new_type((705,), "UNKNOWN", ext.UNICODE))
>>> cur.execute("SELECT '日本語' AS japanese;")
>>> cur.fetchall()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/cursor.
py", line 26, in check_closed_
    return func(self, *args, **kwargs)
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/cursor.
py", line 39, in check_no_tuples_
    return func(self, *args, **kwargs)
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/cursor.
py", line 373, in fetchall
    return [self._build_row() for _ in xrange(size)]
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/cursor.
py", line 884, in _build_row
    self._casts[i], val, length, self)
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/typecas
ts.py", line 70, in typecast
    return caster.cast(value, cursor, length)
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/typecas
ts.py", line 37, in cast
    return self.py_caster(value, cursor)
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/typecas
ts.py", line 38, in cast
    return self.caster(value, length, cursor)
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/site-packages/psycopg2cffi/_impl/typecas
ts.py", line 224, in parse_unicode
    return value.decode(cursor._conn._py_enc) if value is not None else None
  File "/Users/amjith/.virtualenvs/testpsycopgffi/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
>>>
```

This works correctly in `psycopg2` 2.5.4 and returns unicode.

**Comment by lopuhin** [comment]
This works for psycopg2cffi<2.6, it was broken in py3 branch. Thank you for reporting!

**Comment by lopuhin** [comment]
Should be fixes on master (542bc82a7b0 and fc81835ebe3f87), will upload to pypi on sunday evening - still waiting for feedback on another issue.

**Comment by lopuhin** [comment]
released on pypi, closing

**Comment by amjith** [comment]
Verify it on my end. It is now fixed in the new version. 

Thank you for the quick turn around. :)
