### ISSUE TITLE
version mismatch, 1.3.0 != 1.2.1

### ISSUE THREAD

**Issue by vukasin0** [chtd/psycopg2cffi#51]
I'm trying to setup **pypy 2.6.1** with latest **psycopg2cffi** and Django (on fedora21/centos7) but I'm getting strange error.

### Software versions:

 - Django 1.8.4
 - Postgres 9.4.4
 - PyPy from:
    https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.6.1-linux_x86_64-portable.tar.bz2

### Python modules:

    $ pip freeze
      backports.ssl-match-hostname==3.4.0.2
      cffi==1.2.1
      decorator==3.4.0
      Django==1.8.4
      django-filter==0.11.0
      djangorestframework==3.2.3
      iniparse==0.4
      Markdown==2.6.2
      psycopg2cffi==2.7.2
      pycparser==2.14
      pycurl==7.19.3.1
      pygobject==3.14.0
      pygpgme==0.3
      pyliblzma==0.5.3
      pyxattr==0.5.3
      rpm-python==4.12.0.1
      six==1.9.0
      slip==0.6.3
      slip.dbus==0.6.3
      urlgrabber==3.10.1
      yum-metadata-parser==1.1.4

### Steps to reproduce:

    $ export PYTHONPATH=/usr/lib64/python2.7/site-packages:/usr/lib/python2.7/site-packages
    $ ./pypy ~/Development/workspace/python/easycollab/manage.py runserver 0.0.0.0:8001

    ================================================================================

    Found libpq at:
     -> /usr/lib64/libpq.so

    ================================================================================
    Traceback (most recent call last):
      File "/home/vukasin/Development/workspace/python/easycollab/manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
        settings.INSTALLED_APPS
      File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
        self._setup(name)
      File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
        self._wrapped = Settings(settings_module)
      File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/home/vukasin/Downloads/pypy-2.6.1-linux_x86_64-portable/lib-python/2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/vukasin/Development/workspace/python/easycollab/easycollab/settings.py", line 15, in <module>
        from psycopg2cffi import compat
      File "/usr/lib64/python2.7/site-packages/psycopg2cffi/__init__.py", line 4, in <module>
        from psycopg2cffi import extensions
      File "/usr/lib64/python2.7/site-packages/psycopg2cffi/extensions.py", line 39, in <module>
        from psycopg2cffi._impl import connection as _connection
      File "/usr/lib64/python2.7/site-packages/psycopg2cffi/_impl/connection.py", line 10, in <module>
        from psycopg2cffi._impl import exceptions
      File "/usr/lib64/python2.7/site-packages/psycopg2cffi/_impl/exceptions.py", line 12, in <module>
        from psycopg2cffi._impl.libpq import libpq, ffi
      File "/usr/lib64/python2.7/site-packages/psycopg2cffi/_impl/libpq.py", line 4, in <module>
        from psycopg2cffi._impl._build_libpq import ffi, C_SOURCE, C_SOURCE_KWARGS
      File "/usr/lib64/python2.7/site-packages/psycopg2cffi/_impl/_build_libpq.py", line 210, in <module>
        ffi = FFI()
      File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 59, in __init__
        "version mismatch, %s != %s" % (backend.__version__, __version__)
    AssertionError: version mismatch, 1.3.0 != 1.2.1

**Comment by lopuhin** [comment]
cffi complains that cffi backend bundled inside pypy (version 1.3.0) does not match cffi installed elsewhere (1.2.1). Why do you add ``export PYTHONPATH=/usr/lib64/python2.7/site-packages:/usr/lib/python2.7/site-packages`` - are you sure these are from pypy installation? Looking at the traceback I suspect that this are from you CPython install, and this is why there is confusion of version.
I think the best way is to create a virtualenv with pypy and install everything there, and do not modify PYTHONPATH.

**Comment by vukasin0** [comment]
@lopuhin  - thanks for pointing on this - I was doing things totally incorrect.

Here is right way (global setup - in my case Docker image):

#### Download, extract, install and link pypy and pip (pypy version)
##### pypy
> $ wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.6.1-linux_x86_64-portable.tar.bz2
> $ mv pypy-2.6.1-linux_x86_64-portable /usr/local
> $ ln -s  /usr/local/pypy-2.6.1-linux_x86_64-portable/bin/pypy /usr/bin/pypy

##### pip
> $ curl -SL 'https://bootstrap.pypa.io/get-pip.py' | pypy
> $ ln -s  /usr/local/pypy-2.6.1-linux_x86_64-portable/bin/pip /usr/bin/pip

##### Install dependencies
> $ pip install django

##### Test
> $ pypy -c "import django"
