### ISSUE TITLE
Cannot map to psycopg2

### ISSUE THREAD

**Issue by Kadrian** [chtd/psycopg2cffi#60]
```
Python 2.7.9 (9c4588d731b7, Mar 23 2015, 16:20:40)
[PyPy 2.5.1 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> from psycopg2cffi import compat
>>>> compat.register()
>>>> psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: global name 'psycopg2' is not defined
```

Is there something I'm missing?

**Comment by lopuhin** [comment]
``compat.register`` registers ``psycopg2`` as an alias for ``psycopg2cffi``, but you still need to import it:
```
>>> from psycopg2cffi import compat
>>> compat.register()
>>> psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'psycopg2' is not defined
>>> import psycopg2
>>> psycopg2
<module 'psycopg2cffi' from 'psycopg2cffi/__init__.pyc'>
```

**Comment by lopuhin** [comment]
I tried to clarify it in the README - does it look better now?

**Comment by Kadrian** [comment]
Aha! :-) Thanks for clarification!

**Comment by lopuhin** [comment]
You're welcome! :)
