### ISSUE TITLE
Can't decode ascii exception messages

### ISSUE THREAD

**Issue by raimonesteve** [chtd/psycopg2cffi#75]
Hie,

working with psycopg2cffi backend, in exception database (SQL constrains) can't encode ASCII character.

Is it possible exceptions database to encoding with unicode?

More information:
https://bugs.tryton.org/issue6128

The traceback:

> Traceback (most recent call last):
>   File "/home/xxx/tryton/trytond/trytond/protocols/dispatcher.py", line 160, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
>   File "/home/xxx/tryton/trytond/trytond/modules/account_parent_code/account.py", line 98, in create
    accounts = super(Account, cls).create(vlist)
>   File "/home/xxx/tryton/trytond/trytond/model/modelsql.py", line 558, in create
    exception, values, transaction=transaction)
>   File "/home/xxx/tryton/trytond/trytond/model/modelsql.py", line 307, in __raise_integrity_error
    if name in str(exception):
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 31: ordinal not in range(128)

**Comment by lopuhin** [comment]
Hi, thanks for the bug report! ``str(exception)`` definitely should not fail, I'll try to figure out why that happens.

**Comment by dabada83** [comment]
Try with this:

def __str__(self):
    return unicode(self.message).encode('utf-8')

inside Error class
